### ISSUE TITLE
script misses a word depending on comment formats

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/parse_clan#1]
when running parseclan on 22_06_coderEB_error.cex (in seedlings drive), whether or not it finds the second instance of word 'shadow' depends on some weird formatting issue: putting '%com: end skip' right before the 'shadow' line makes the word be found as usual, omitting the comment causes the script to skip it:
WITHOUT comment line:
*FAN,toy,q,y,MOT,36218710_36220730,NA
*FAN,diaper,n,y,FAT,42313860_42315180,NA

vs.
WITH comment line
*FAN,toy,q,y,MOT,36218710_36220730,NA
*FAN,shadow,q,y,MOT,36291020_36292110,NA
*FAN,diaper,n,y,FAT,42313860_42315180,NA

(pasted from the terminal output)

**Comment by URBabylab** [comment]
So the current code doesn't include object words between "begin skip" and "end skip," it was the same issue with Valerie except she misspelled "end skip" to "end_skip" which meant that all the words recorded afterwards weren't recognized. 

I'll just have it output in an error if an object word is found within a skip

**Comment by ebergelson** [comment]
wait no, that's what it should do! there shouldn't be object words coded
during skips! but it should print an error to the terminal saying it did so.
can we fix this and make a note on the wiki?
thnx
e

   _Elika Bergelson, PhD_
Research Assistant Professor, University of Rochester
 Center for Language Sciences | Brain and Cognitive Science Dept. |
www.bcs.rochester.edu/people/ebergelson | www.bcs.rochester.edu/seedlings/
    Get a signature like this:
https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9
Click
here!
https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9

**Comment by ebergelson** [comment]
not print an error, print a message. and people should check that message.
this should all be added to the wiki.

**Comment by URBabylab** [comment]
Yep, didn't want to change the object words not recording in skips. Will there ever be object words in a skip if we coded correctly? If not, it might be best to not even create a .csv file and output an error instead, in case people don't check the terminal window for messages and don't notice that words are missing in the .csv. That forces them to make sure that the skips are placed in the right place.

Also, tomorrow I'm going to do a quick check on random files to make sure that this wasn't a gigantic issue.

**Comment by ebergelson** [comment]
yeah there shouldn't be object words in skips but you could imagine that
someone might choose to skip a region after having coded it a bit or
something. whatever you think is easiest for people. By the way I'm
assuming that the URBabylab messages are coming from Munna but if it's
Andrei or someone else let me know..:)

   _Elika Bergelson, PhD_
Research Assistant Professor, University of Rochester
 Center for Language Sciences | Brain and Cognitive Science Dept. |
www.bcs.rochester.edu/people/ebergelson | www.bcs.rochester.edu/seedlings/
    Get a signature like this:
https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9
Click
here!
https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9

**Comment by URBabylab** [comment]
It's Munna haha, so for now I just created a message asking to make sure that no object words occur within skips since we've been telling people skips are regions with no talking and I could totally see someone not paying attention to the terminal window if they get a .csv with words. depending on what issues come up we can change this pretty easily!
